# Modified from the official one but does run it which we don't want
# https://github.com/pre-commit/action/blob/main/action.yml

name: install pre-commit
description: "install pre-commit but don't run it"
runs:
    using: composite
    steps:
        - run: python -m pip install pre-commit
          shell: bash
        - run: python -m pip freeze --local
          shell: bash
        - uses: actions/cache@v3
          with:
              path: ~/.cache/pre-commit
              key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
