name: "Who's Changed"

on:
    workflow_call:
        outputs:
            # Map the job outputs to the workflow outputs:
            docs-changed:
                description: Whether files relating to docs have changed or not
                value: ${{ jobs.whos_changed.outputs.docs-changed }}
            py-changed:
                description: Whether files relating to py have changed or not
                value: ${{ jobs.whos_changed.outputs.py-changed }}

jobs:
    whos_changed:
        runs-on: ubuntu-latest
        # Map the outputs:
        outputs:
            docs-changed: ${{ steps.check.outputs.docs-changed }}
            py-changed: ${{ steps.check.outputs.py-changed }}

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - uses: dorny/paths-filter@v2
              id: check
              with:
                  filters: |
                      docs-changed:
                        - 'docs/**'
                        - 'mkdocs.yml'
                      py-changed:
                        - 'python/**'
